# Generated by Django 4.1.7 on 2023-03-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='name',
            new_name='island',
        ),
        migrations.RenameField(
            model_name='finch',
            old_name='scientific_name',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='finch',
            name='image_url',
        ),
        migrations.AddField(
            model_name='finch',
            name='beak_depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='finch',
            name='beak_width',
            field=models.FloatField(default=0.0),
        ),
    ]
